"use strict";
exports.__esModule = true;
var isBeginner = true;
var total = 0;
var name = 'Nilank Nikhil';
var sentence = "My name is " + name + "\nI am a beginner in Typescript";
console.log(sentence);
var n = null;
var u = undefined;
var isNew = null;
var myName = undefined;
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var person1 = ['Nilank', 22];
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Green;
console.log(c);
(function (Color) {
    Color[Color["Pink"] = 5] = "Pink";
    Color[Color["Black"] = 6] = "Black";
    Color[Color["Yellow"] = 7] = "Yellow";
})(Color || (Color = {}));
;
var d = Color.Black;
console.log(d);
